In [39]:
import torch
import numpy as np

In [5]:
x = torch.randn(3, requires_grad = True)

In [6]:
x

tensor([ 0.3276, -0.2056, -0.0355], requires_grad=True)

In [8]:
y = x + 2
y

tensor([2.3276, 1.7944, 1.9645], grad_fn=<AddBackward0>)

In [10]:
z = y*y*2
z

tensor([10.8350,  6.4396,  7.7189], grad_fn=<MulBackward0>)

In [11]:
z = z.mean()
z

tensor(8.3312, grad_fn=<MeanBackward0>)

In [12]:
z.backward()
z

tensor(8.3312, grad_fn=<MeanBackward0>)

In [26]:
x.grad

In [27]:
x.requires_grad_(False)
x.detach()


tensor([ 0.3452, -0.6222, -0.1104])

In [29]:
with torch.no_grad():
    y = x+2
y

tensor([2.3452, 1.3778, 1.8896])

In [32]:
weights = torch.ones(4, requires_grad = True)

for epoch in range(3):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [33]:
weights = torch.ones(4, requires_grad = True)

optimizer = torch.optim.SGD(weights, lr = 0.01)
optimizer.step()
optimizer.zero_grad()

TypeError: params argument given to the optimizer should be an iterable of Tensors or dicts, but got torch.FloatTensor

In [34]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)

w = torch.tensor(1.0, requires_grad = True)

In [35]:
y_hat = w * x
loss = (y_hat -y)**2

print(loss)

tensor(1., grad_fn=<PowBackward0>)


In [42]:
loss.backward(retain_graph=True)
w.grad

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.