In [1]:
import torch

In [7]:
x = torch.empty(3,2,2,3)
print(x)

tensor([[[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]]])


In [3]:
x = torch.rand(2,3)
print(x)

tensor([[0.8890, 0.1668, 0.5496],
        [0.5792, 0.9747, 0.6186]])


In [5]:
x = torch.ones(2,3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [8]:
x = torch.empty(2,3, dtype = torch.float64)
print(x.dtype)

torch.float64


In [9]:
print(x.size())

torch.Size([2, 3])


In [10]:
x = torch.tensor([2,3,4,5])

In [11]:
print(x)

tensor([2, 3, 4, 5])


In [12]:
x = torch.rand(2,3)
y = torch.rand(2,3)
print(x, '\n', y)

tensor([[0.2788, 0.9103, 0.2243],
        [0.7890, 0.4138, 0.1621]]) 
 tensor([[0.7143, 0.0475, 0.7511],
        [0.9744, 0.5486, 0.0552]])


In [14]:
z = x + y
print(z)
y.add_(x)
print(y)

tensor([[0.9931, 0.9578, 0.9754],
        [1.7634, 0.9625, 0.2173]])
tensor([[0.9931, 0.9578, 0.9754],
        [1.7634, 0.9625, 0.2173]])


In [15]:
z = torch.sub(y,x)
w = torch.mul(x,y)

print(z,'\n',w)

tensor([[0.7143, 0.0475, 0.7511],
        [0.9744, 0.5486, 0.0552]]) 
 tensor([[0.2768, 0.8719, 0.2188],
        [1.3914, 0.3983, 0.0352]])


In [16]:
x = torch.rand(5,3)
print(x)

tensor([[0.7314, 0.1056, 0.7562],
        [0.3655, 0.0093, 0.2237],
        [0.5903, 0.0467, 0.6558],
        [0.7934, 0.0545, 0.8295],
        [0.1177, 0.1741, 0.5619]])


In [25]:
print(x[3:,2])

tensor([0.8295, 0.5619])


In [24]:
print(x[4,2].item())

0.5619179010391235


In [26]:
x = torch.rand(4,4)
print(x)
y = x.view(16)
print(y)

tensor([[0.5093, 0.8170, 0.6679, 0.3754],
        [0.3905, 0.0946, 0.5535, 0.8454],
        [0.2052, 0.4640, 0.2447, 0.4384],
        [0.6158, 0.1138, 0.0252, 0.0076]])
tensor([0.5093, 0.8170, 0.6679, 0.3754, 0.3905, 0.0946, 0.5535, 0.8454, 0.2052,
        0.4640, 0.2447, 0.4384, 0.6158, 0.1138, 0.0252, 0.0076])


In [28]:
y = x.view(1,16)
print(y)

tensor([[0.5093, 0.8170, 0.6679, 0.3754, 0.3905, 0.0946, 0.5535, 0.8454, 0.2052,
         0.4640, 0.2447, 0.4384, 0.6158, 0.1138, 0.0252, 0.0076]])


In [29]:
y = x.view(-1,8)
print(y)

tensor([[0.5093, 0.8170, 0.6679, 0.3754, 0.3905, 0.0946, 0.5535, 0.8454],
        [0.2052, 0.4640, 0.2447, 0.4384, 0.6158, 0.1138, 0.0252, 0.0076]])


In [31]:
y = x.view(8,2)
print(y)

tensor([[0.5093, 0.8170],
        [0.6679, 0.3754],
        [0.3905, 0.0946],
        [0.5535, 0.8454],
        [0.2052, 0.4640],
        [0.2447, 0.4384],
        [0.6158, 0.1138],
        [0.0252, 0.0076]])


In [32]:
import numpy as np

In [33]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b, type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


In [34]:
a.add_(1)
print(a,b)

tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


In [36]:
a = np.ones(5)
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [37]:
a += 1
print(a,b)

[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [38]:
x = torch.ones(5, requires_grad = True)